import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

const indexPath = new URL("../public/index.html", import.meta.url);
const appPath = new URL("../public/app.js", import.meta.url);

test("UI includes a reset call control wired to restart the session", async () => {
  const [html, app] = await Promise.all([
    readFile(indexPath, "utf8"),
    readFile(appPath, "utf8")
  ]);

  assert.match(html, /id="resetButton"/);
  assert.match(html, /Reset Call/);
  assert.match(html, /id="micToggleButton"/);
  assert.match(html, /id="callButtonLabel"/);
  assert.match(html, /Start Absentee Call/);
  assert.match(html, /id="hallPassButton"/);
  assert.match(html, /Start Hall Pass Call/);
  assert.match(html, /id="caseStrip" hidden/);
  assert.doesNotMatch(html, /Loading attendance case/);
  assert.match(html, /Enable Mic/);
  assert.doesNotMatch(html, /id="stopButton"/);
  assert.match(html, /role="tablist"/);
  assert.match(html, /id="systemTab"/);
  assert.match(html, /id="systemView"/);
  assert.match(html, /System architecture/);
  assert.match(html, /Use case processes/);
  assert.match(html, /Use Case: Teacher Records Attendance/);
  assert.match(html, /Use Case: Student Uses Hall Pass/);
  assert.match(html, /Use Case: ABE Evaluates Risk And Policy/);
  assert.match(html, /Use Case: Voice Agent Calls Guardian/);
  assert.match(html, /<svg class="architecture-diagram"/);
  assert.match(html, /<svg class="process-diagram"/);
  assert.match(html, /id="themeToggle"/);
  assert.match(html, />ABE</);
  assert.match(html, />Data</);
  assert.match(html, />Logic</);
  assert.match(html, />Policy</);
  assert.doesNotMatch(html, /Attendence Bot \+ E/);
  assert.doesNotMatch(html, /Data: students, guardians, events/);
  assert.doesNotMatch(html, /Logic: trends, queues, thresholds/);
  assert.doesNotMatch(html, /Policy: district guidance and LLM/);
  assert.doesNotMatch(html, /Attendance entry/);
  assert.doesNotMatch(html, /history review/);
  assert.doesNotMatch(html, /Bilingual guardian call/);
  assert.doesNotMatch(html, /excuse capture/);
  assert.doesNotMatch(html, /attendance event/);
  assert.doesNotMatch(html, /hall pass event/);
  assert.doesNotMatch(html, /guardian call task/);
  assert.doesNotMatch(html, /excuse result/);
  assert.doesNotMatch(html, /updated status/);
  assert.match(html, /View Dashboard/);
  assert.match(html, /Update Status/);
  assert.match(html, /Start Hall Pass/);
  assert.match(html, /Return Hall Pass/);
  assert.match(html, /Load Students/);
  assert.match(html, /Call Guardian/);
  assert.match(html, /Record Conversation/);
  assert.doesNotMatch(html, /class="step-copy"/);
  assert.doesNotMatch(html, /Core Data Store/);
  assert.doesNotMatch(html, /Core Logic and Policy/);
  assert.match(html, /href="\.\/styles\.css"/);
  assert.match(html, /src="\.\/app\.js"/);
  assert.match(app, /restartSession/);
  assert.match(app, /resetButton\.addEventListener/);
  assert.match(app, /toggleMicrophoneListening/);
  assert.match(app, /micToggleButton\.addEventListener/);
  assert.match(app, /setCallButtonStarted/);
  assert.match(app, /isCaseSummaryVisible/);
  assert.match(app, /hideCaseSummary/);
  assert.match(app, /End Call/);
  assert.match(app, /callScenarios/);
  assert.match(app, /caseSummary/);
  assert.match(app, /has had 14 hall passes in the last 10 school days for a total of 4 hours of time outside class/);
  assert.match(app, /Start Absentee Call/);
  assert.match(app, /Start Hall Pass Call/);
  assert.match(app, /Do not substitute a different attendance issue/);
  assert.match(app, /use it only as a tie-breaker for ambiguous one-word replies/);
  assert.match(app, /If the guardian says "yes", continue in English/);
  assert.match(app, /If the guardian says "sí" or "si", continue in Spanish/);
  assert.match(app, /Would you prefer English or Spanish\? ¿Prefiere inglés o español\?/);
  assert.match(app, /Data Saved/);
  assert.doesNotMatch(app, /data\/output\/conversations\.csv/);
  assert.doesNotMatch(app, /Realtime session created/);
  assert.doesNotMatch(app, /Excuse saved as/);
  assert.match(app, /hallPassButton\.addEventListener/);
  assert.match(app, /setMicrophoneListening\(false\)/);
  assert.match(app, /Mic paused/);
  assert.match(app, /transcriptLabelFor/);
  assert.match(app, /assistant: "ABE"/);
  assert.match(app, /parent: "GUARDIAN"/);
  assert.doesNotMatch(app, /stopButton/);
  assert.match(app, /activateTab/);
  assert.match(app, /systemTab\.addEventListener/);
  assert.match(app, /toggleTheme/);
  assert.match(app, /attendanceOfficerTheme/);
  assert.match(app, /Hello this is Abe calling from the Austin High School\. Is this/);
  assert.match(app, /apiPath/);
  assert.match(app, /http:\/\/localhost:5178/);
  assert.match(app, /startListenOnlySession/);
  assert.match(app, /recvonly/);
  assert.match(app, /Microphone Blocked/);
});
